controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

wheel_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint